---
version: "3.3"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Denver
     # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin #optional
      - PASS=#Hab%m(6c) #optional
      - WHITELIST= #optional
      - HOST_WHITELIST=dnsname list #optional
      - LOCAL_NETWORK=10.20.62.0/24,192.168.186.0/24,192.168.184.0/24
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_USERNAME=3235274025754658
      - OPENVPN_PASSWORD=m
      - OPENVPN_CONFIG=us_slc
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - '/srv/dev-disk-by-uuid-4965017e-fe39-4b7d-85ba-f69e4e87ef27/AMACloudMovies:/data'
      - '/srv/dev-disk-by-uuid-fde7d6f8-f441-434d-a5f3-2c763542f667/AMACloudMovies2:/data2'
    ports:
      - 55277:9091
      - 8888:8888
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
